spring.application.name=java-orm

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/test
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=test
spring.datasource.password=test

# more threads
server.tomcat.max-threads=200      # Maximum number of threads
server.tomcat.min-spare-threads=20 # Minimum number of spare threads

# HikariCP Pool Settings
spring.datasource.hikari.minimum-idle=15
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=300
spring.datasource.hikari.max-lifetime=600000

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true